version: '3'
services:
  container:
    ports:
      - '6666:8000' # Remote debugging port
    environment:
      PUBLIC_HOSTNAME: <your public ip address>
      CONTAINER_REPOSITORY_HOSTNAME: <your public ip address>
      # CONTAINER_DEPLOYMENT_TESTS: 'true'
      CONTAINER_JAVA_OPTS: |-
        -Xdebug
        -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
    # volumes:
    #   - <path on host system>:/tmp/opentosca
  container-repository:
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
  engine-plan:
    ports:
      - '5555:8000' # Remote debugging port
    environment:
      JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
  engine-ia:
    # volumes:
    #   - <path on host system>:/usr/local/tomcat/webapps
    # ports:
    #   - '1883:1883' # MQTT
  container-repository:
    environment:
      WINERY_HOSTNAME: <your public ip address>
      # WORKFLOWMODELER_HOSTNAME: <your public ip address>
      # TOPOLOGYMODELER_HOSTNAME: <your public ip address>
      # CONTAINER_HOSTNAME: <public ip address of the container>
  winery:
    environment:
      WINERY_REPOSITORY_URL: https://github.com/OpenTOSCA/tosca-definitions-public
      # WINERY_HOSTNAME: <your public ip address>
      # WORKFLOWMODELER_HOSTNAME: <your public ip address>
      # TOPOLOGYMODELER_HOSTNAME: <your public ip address>
      # CONTAINER_HOSTNAME: <public ip address of the container>

  dind:
    environment:
      # University of Stuttgart internal DNS settings
      - DOCKER_DAEMON_ARGS=--dns 129.69.211.1 --dns 129.69.215.5 -D
    ports:
      - '9990-9999:9990-9999'
    # volumes:
    #   - '/var/run/docker.sock:/var/run/docker.sock'
